### PR TITLE
10.0 callino rebase

### PR DESCRIPTION
**Pull request by wpichler**
hi,

this is the current version - crud operations on product.attributes are working - but needs more testing

### CODE REVIEW

**Comment by flotho** [comment]
Dear @wpichler ,
You made so many improvements, thanks for this effort. Could you tell me when I can test your PR, do you consider it as mature ?
regards

**Comment by wpichler** [comment]
Dear @flotho There are still some changes to come - i found some problems with the generation of the variants on product template import.
The attribute sync can be considered as stable - the product template should get stable today.
Then i will check the sale order import...

**Comment by flotho** [comment]
Hi @wpichler ,

I've corrected a conflict. Could you please explain why you think that the sale ordr process has changed ? 
AFAIK, only product.product are used so do you consider that your improvements could have an impact on the import process ?
regards

**Comment by wpichler** [comment]
@flotho I don't know if the sale order process has changed - thats why i'd like to check it - and if there is a problem i will try to fix it.
An other small thing i will add now - is tax rule mapping

**Comment by flotho** [comment]
Thanks @wpichler ,
great way to proceed, thanks for sharing

**Comment by wpichler** [comment]
Did a rebase onto mindandgo 10.0-components-magento2 to resolv conflicts

**Comment by wpichler** [comment]
I will work today on order workflow - import order / create invoice / create picking - transmit carrier code...

**Comment by wpichler** [comment]
First thing which is missing here - is to import the payment - if there is already one - i will do this now...

**Comment by flotho** [comment]
Hi @wpichler ,
Thanks I'll merge your PR and test it today.
regards

**Comment by flotho** [comment]
Hi @wpichler ,

I'm merging your work and testing it. Please reopen a new PR if needed

**Comment by wpichler** [comment]
ok

**Pull request merged**
