### PR TITLE
10.0 callino rebase

### PR DESCRIPTION
**Pull request by wpichler**
New PR with conflicts fixed

### CODE REVIEW

**Comment by flotho** [comment]
Dear @wpichler 
Thanks for this PR. I'm reporting here your original one https://github.com/MindAndGo/connector-magento/pull/1 
Moreover I would like to react to your comment :
> I will rebase today.
For this week we also want to work on the import logic - test it against the customer magento2 setup - and the customer odoo setup. Also for this week we do focus on the configurable import.
For the next week we do plan to add some more export functions - mainly to export products / configurable products

If you we're not aware of it, please consider that the export mechanism are mainly implemented in this repo :

- For the partner : https://github.com/MindAndGo/connector-magento/tree/10.0-components-magento2/connector_magento_export_partner
- For the product : https://github.com/MindAndGo/connector-magento/tree/10.0-components-magento2/connector_magento_product_catalog

Did you already tried the latest one. The workflow is to create bindings from product.template and to export it as a configurable or not regarding of the presence of variants. The code concerned is there https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento_product_catalog/models/product_template/exporter.py#L120 and there https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento_product_catalog/models/product_template/common.py#L41
Then it export product.product always as magento simple products thanks to dependencies : https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento_product_catalog/models/product_template/exporter.py#L26 and finally it's binding the template as configurable to product as simple thanks to https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento_product_catalog/models/product_template/exporter.py#L136 and https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento_product_catalog/models/product_template/exporter.py#L157
This part has been successfully tested but maybe needs for tests.
Moreover we developed a mechanism for custom attributes as defined in the magento API and you could bind magento_product_attribute to an internal Odoo field so that updating one in odoo is automatically updating the custom attributes. This is the part : https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento_product_catalog/models/product_template/exporter.py#L225

Could you confirm that you already saw this part of the implementation? It has been a long road to develop this and updating it thanks to your work should be more efficient than rewriting all the stuff

**Comment by flotho** [comment]
@wpichler , please also consider to use your same branch that will me marked as WIP

**Comment by wpichler** [comment]
@flotho I've seen the product_catalog module and the export_partner module. We do not want to duplicate work...
I will rebase on your WIP branch - and create PR's on this

**Comment by flotho** [comment]
Hi @wpichler , thanks for the answer.
Bad information from me. https://github.com/MindAndGo/connector-magento/tree/10.0-components-magento2 still the branch you need to rebase. 
Regards

**Comment by wpichler** [comment]
@flotho Ok - no problem. For your information - i do currently work on attribute / attribute value import / export. Looks quit good already

**Pull request merged**
