### PR TITLE
10.0 callino rebase

### PR DESCRIPTION
**Pull request by wpichler**
Created this PR so that you can watch progress - to avoid duplicate work...
Working hard on attribute export - not finished completly

### CODE REVIEW

**Comment by flotho** [comment]
Great thanks for sharing

**Comment by flotho** [comment]
Hi @wpichler ,

I'm merging your PR because some fix are needed for my projects.

**Comment by flotho** [comment]
@wpichler ,

Please consider to submit your next PR in the same way as this one,
Thanks

**Comment by flotho** [comment]
Hi @wpichler ,

Di you tried to import the attributes set ? it looks like something is broken :

```
agento_binding/common.py", line 53, in import_record
    return importer.run(external_id, force=force)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector-magento/connector_magento/components/importer.py", line 220, in run
    self._after_import(binding)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector-magento/connector_magento/models/attributes_set/importer.py", line 68, in _after_import
    importer.run(record.get('attribute_id'))
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector-magento/connector_magento/components/importer.py", line 216, in run
    binding = self._create(record)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector-magento/connector_magento/components/importer.py", line 154, in _create
    binding = model.create(data)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector/connector/producer.py", line 30, in create
    record = super(Base, self).create(vals)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector/component_event/models/base.py", line 95, in create
    record = super(Base, self).create(vals)
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/models.py", line 3851, in create
    record = self.browse(self._create(old_vals))
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/models.py", line 4000, in _create
    field.write(self.with_context(rel_context), vals[name])
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/fields.py", line 2226, in write
    comodel.create(act[2])
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector/connector/producer.py", line 30, in create
    record = super(Base, self).create(vals)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector/component_event/models/base.py", line 95, in create
    record = super(Base, self).create(vals)
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/models.py", line 3851, in create
    record = self.browse(self._create(old_vals))
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/models.py", line 3912, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-product-variant/product_variant_default_code/models/product.py", line 271, in create
    return super(ProductAttributeValue, self).create(vals)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector/connector/producer.py", line 30, in create
    record = super(Base, self).create(vals)
  File "/home/florent/DEV/_EclipseOdoo/Oropa/Libs/OCA-connector/component_event/models/base.py", line 95, in create
    record = super(Base, self).create(vals)
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/models.py", line 3851, in create
    record = self.browse(self._create(old_vals))
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/models.py", line 3946, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/florent/DEV/Odoo_Server_And_Libs/Servers_10/OCB/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "attribute_id" violates not-null constraint
DETAIL:  Failing row contains (9452, 1, Ensemble, null, null, 2019-03-19 09:57:20.12733, 2019-03-19 09:57:20.12733, 1, En, null).
```

**Comment by wpichler** [comment]
WIP - i have done some rewrites here - and will finish it today

**Comment by wpichler** [comment]
it will support full CRUD Operations for Attributes and Values - From Odoo to Magento - and From Magento to Odoo if requested by user...

**Comment by flotho** [comment]
could you push your work so that I don't do the fix twice ;-) ?

**Comment by wpichler** [comment]
I've pushed the current state - now i do work on it to finish it today

**Comment by flotho** [comment]
Hi @wpichler , sorry but where did you pushed it ?

**Comment by wpichler** [comment]
I've now created a new PR for it

**Pull request merged**
