### PR TITLE
New PR for the next updates / fixes

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Comment by wpichler** [comment]
@flotho FYI i will be working on stock interface today...

**Comment by flotho** [comment]
hi @wpichler ,

You're rocking man...

**Comment by flotho** [comment]
Hi @wpichler ,
could you give me some infos about this https://github.com/MindAndGo/connector-magento/commit/c70fb8a4035ef138ab214542c6ceab33801d7936#r32918457

**Comment by flotho** [comment]
hi @wpichler ,
I'm not sure of the reason why you add the binding there : https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento/components/exporter.py#L328 . Your commit message indicates you made this for crud on attribute export, yet you override the process there : https://github.com/MindAndGo/connector-magento/blob/10.0-components-magento2/connector_magento/models/attribute/exporter.py#L20

FMO, you should come back to the old old process in the exporter part.

**Comment by wpichler** [comment]
I've generally added binding as a new argument to the backend adapter create function - because  some magent2 rest api calls need more information than only the current external id. Often the need information about the parent object - and using the binding you are able to get the information from the parent object.

But you are also correct - currently - with only the attributes export it would not be necessary to generally pass the binding object - because i have complete overwriten the functions for the attributes - but i think it will get necessary when implementing the complete product export - and thats why i left it there

**Comment by flotho** [comment]
@wpichler , 
from now i'm testing the export and this change broke the previous process.
could we revert this until the exportation product has been retested by me from A to Z ?
regards

**Comment by flotho** [comment]
my bad for the UPPER,  I have to replace my keyboard ;-)

**Comment by flotho** [comment]
@wpichler , 

additionnal question from here, how do you handle the Sku of the configurable ? where do you store it when you have variants ?

**Comment by wpichler** [comment]
@flotho can you show me what is broken with this change ? because i added the argument with binding=None - to be backwards compatible - so it should not break things...

About the sku on configurables - the sku i do use is in the binding the field external_id. So you could have different default_code in odoo compared to magento sku per backend...

**Comment by flotho** [comment]
@wpichler 

the magento 2 process for creating product through api needs SKU so when working with configurables it's not possible to have the default_code of the template to be the same as the first variant. this is a requirement of the odoo TO  magento process. so I propose to add a dedicated default code for magento in the template. Nothing will change for your process and the Odoo -> Magento flow will be operationnal.
Regarding the create method I'll make nex tests with your original code.

regards

**Comment by wpichler** [comment]
@flotho You are right - for the export we will need the sku of the template.

**Comment by flotho** [comment]
@wpichler 

thanks for the sharing of your expertise.
I merge your PR so we could progress on the tests , 
read you in the next PR ;-)

**Pull request merged**
