### PR TITLE
10.0 callino

### PR DESCRIPTION
**Pull request by wpichler**
Added support for importing configurable products

### CODE REVIEW

**Comment by flotho** [comment]
Dear @wpichler ,
Thanks for your PR. I didn't saw it before.
Is it possible for you to rebase  your branch so that I could have a look in better condition?
So many improvements in your PR.
Thansk

**Comment by wpichler** [comment]
We will work on this branch the next two weeks - and will make some more improvements. So i would be happy if you could tell me if you are also working on something on this branch - so that no duplicate work does happen.
On which branch should we rebase ?

**Comment by flotho** [comment]
Additionnaly, in my opinioin it would be better to handle the configurable import into the catalog manager.
The connector_magento has not been designed to handle configurable by default and moreover the product_catalog we developped is designed to handle complex organisation of product so maybe you could move this part in the catalog manager module?

**Comment by flotho** [comment]
@wpichler ,

This branch is our main branch, you could use it for rebase.
Actually, we're working on small patches either. since now we'll work with PR into this one so that we would be able to progress together.

For the same reason as yours, could you share with us the roadmap you have for the next two weeks so that  we won't get in weird useless conflicts between our code.

**Comment by wpichler** [comment]
I will rebase today.
For this week we also want to work on the import logic - test it against the customer magento2 setup - and the customer odoo setup. Also for this week we do focus on the configurable import.
For the next week we do plan to add some more export functions - mainly to export products / configurable products

**Comment by wpichler** [comment]
I've created a new PR with conflicts resolved - please take a look at it

**Pull request closed without merging**
